---
version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
       POSTGRES_PASSWORD: lalala
       POSTGRES_USER: autoclear
    ports:
      - 5433:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 9100:8080

